// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3NM9aFPpN7M4oO9S0ZTXCMm6Y-j_Krow',
    appId: '1:938868509667:web:1248a600ba31b3baeb2ed6',
    messagingSenderId: '938868509667',
    projectId: 'dynamic-ledger-insight',
    authDomain: 'dynamic-ledger-insight.firebaseapp.com',
    storageBucket: 'dynamic-ledger-insight.firebasestorage.app',
    measurementId: 'G-YE7DTE1049',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDogpZFCDeDRT7WFkSk1fQJqV4C99KOxw8',
    appId: '1:938868509667:android:9c9bfbaa03f36b36eb2ed6',
    messagingSenderId: '938868509667',
    projectId: 'dynamic-ledger-insight',
    storageBucket: 'dynamic-ledger-insight.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVDzUd-5dkcZqemIQMOBs-s2DieOwW6Ak',
    appId: '1:938868509667:ios:4cb55b321b977374eb2ed6',
    messagingSenderId: '938868509667',
    projectId: 'dynamic-ledger-insight',
    storageBucket: 'dynamic-ledger-insight.firebasestorage.app',
    iosBundleId: 'com.example.fincontrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVDzUd-5dkcZqemIQMOBs-s2DieOwW6Ak',
    appId: '1:938868509667:ios:4cb55b321b977374eb2ed6',
    messagingSenderId: '938868509667',
    projectId: 'dynamic-ledger-insight',
    storageBucket: 'dynamic-ledger-insight.firebasestorage.app',
    iosBundleId: 'com.example.fincontrol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3NM9aFPpN7M4oO9S0ZTXCMm6Y-j_Krow',
    appId: '1:938868509667:web:67f1a95364b98defeb2ed6',
    messagingSenderId: '938868509667',
    projectId: 'dynamic-ledger-insight',
    authDomain: 'dynamic-ledger-insight.firebaseapp.com',
    storageBucket: 'dynamic-ledger-insight.firebasestorage.app',
    measurementId: 'G-2LB3VBFKJ8',
  );
}
